### ISSUE TITLE
Cannot Access the Mods page or start the server

### ISSUE THREAD

**Issue by jonny190** [wine-gameservers/arch-wine-fs22#11]
Here is a video of the issue 
https://sharex.daveys.xyz/nUha3/gigexuce41.mp4

Below is the Wine crash error: 

Unhandled exception: divide by zero in 64-bit code (0x0000014009d15a).
Register dump:
 rip:000000014009d15a rsp:00007fffff0cf210 rbp:00007fffff0cf340 eflags:00010246 (  R- --  I  Z- -P- )
 rax:0000000000006c34 rbx:0000000000000000 rcx:22cdc088e0920000 rdx:0000000000000000
 rsi:00007fffff0cf2a0 rdi:00007ffffea0bdb0  r8:0000000000006c34  r9:0000000000000001 r10:0000000000000000
 r11:00007fffff0cf200 r12:000000014050e8ec r13:00007ffffea27140 r14:00007fffff0cf580 r15:0000001f78ad8000
Stack dump:
0x007fffff0cf210:  0000000000000000 0000000000000000
0x007fffff0cf220:  00007fffff0cf2a0 00007ffffea0bdb0
0x007fffff0cf230:  000000014050e940 00000001400cf406
0x007fffff0cf240:  0000000000000000 00000000099bb000
0x007fffff0cf250:  0000000000000000 0000000000000000
0x007fffff0cf260:  000000014050e8b8 000000014050e8c0
0x007fffff0cf270:  00007fff3f800000 00007ffffe220000
0x007fffff0cf280:  3c23d70a00000000 00006fff3a9c5005
0x007fffff0cf290:  00007fffff0cf690 00007ffffea2e3c0
0x007fffff0cf2a0:  0000000000000000 0000000000000000
0x007fffff0cf2b0:  0000000000000000 0000000000000115
0x007fffff0cf2c0:  0000000000000000 0000000000000115
Backtrace:
=>0 0x0000014009d15a in dedicatedserver (+0x9d15a) (0x007fffff0cf340)
  1 0x000001400cf406 in dedicatedserver (+0xcf406) (0x007fffff0cf340)
  2 0x000001400ce5e3 in dedicatedserver (+0xce5e3) (0x007fffff0cf630)
  3 0x000001400cc03c in dedicatedserver (+0xcc03c) (0000000000000000)
  4 0x0000014010af98 in dedicatedserver (+0x10af98) (0x007fffff0cfa00)
  5 0x0000014010242d in dedicatedserver (+0x10242d) (0x007fffff0cfba0)
  6 0x00000140107565 in dedicatedserver (+0x107565) (0x0000000100007f)
  7 0x000001401caa44 in dedicatedserver (+0x1caa44) (0000000000000000)
  8 0x006fffffaa8c79 BaseThreadInitThunk+0x9(unknown=<internal error>, entry=<internal error>, arg=<internal error>) [/build/wine/src/wine-64-build/../wine/dlls/kernel32/thread.c:61] in kernel32 (0000000000000000)
  9 0x006fffffca561b in ntdll (+0x5561b) (0000000000000000)
0x0000014009d15a dedicatedserver+0x9d15a: div (%rsi)
Modules:
Module  Address                                 Debug info      Name (81 modules)
PE             140000000-       1405b8000       Export          dedicatedserver
PE-Wine        180000000-       180002000       Deferred        normaliz
PE-Wine     6ffffb450000-    6ffffb745000       Deferred        wldap32
PE-Wine     6ffffba00000-    6ffffba32000       Deferred        kerberos
PE-Wine     6ffffba50000-    6ffffbb05000       Deferred        secur32
PE-Wine     6ffffbb20000-    6ffffbb72000       Deferred        shcore
PE-Wine     6ffffbb90000-    6ffffbca5000       Deferred        shlwapi
PE-Wine     6ffffbcc0000-    6ffffca3c000       Deferred        shell32
PE-Wine     6ffffca50000-    6ffffce0b000       Deferred        crypt32
PE-Wine     6ffffce20000-    6ffffcfb7000       Deferred        combase
PE-Wine     6ffffcfd0000-    6ffffd54c000       Deferred        ole32
PE-Wine     6ffffd560000-    6ffffd715000       Deferred        winmm
PE-Wine     6ffffd730000-    6ffffd9b8000       Deferred        rpcrt4
PE-Wine     6ffffd9e0000-    6ffffd9f1000       Deferred        psapi
PE-Wine     6ffffda10000-    6ffffda6a000       Deferred        bcrypt
PE-Wine     6ffffda80000-    6ffffdacc000       Deferred        coml2
PE-Wine     6ffffdae0000-    6ffffdb5b000       Deferred        msacm32
PE-Wine     6ffffdb70000-    6ffffdb94000       Deferred        nsi
PE-Wine     6ffffdbb0000-    6ffffdbfd000       Deferred        dnsapi
PE-Wine     6ffffdc10000-    6ffffdc9e000       Deferred        iphlpapi
PE-Wine     6ffffdd60000-    6ffffdddd000       Deferred        imm32
PE-Wine     6ffffddf0000-    6ffffde2e000       Deferred        win32u
PE-Wine     6ffffde40000-    6ffffe10a000       Deferred        gdi32
PE-Wine     6ffffe120000-    6ffffe6f8000       Deferred        user32
PE-Wine     6ffffea30000-    6ffffeadc000       Deferred        ws2_32
PE-Wine     6ffffeaf0000-    6ffffeedf000       Deferred        ucrtbase
PE-Wine     6ffffeef0000-    6ffffefae000       Deferred        sechost
PE-Wine     6ffffefc0000-    6fffff311000       Deferred        msvcrt
PE-Wine     6fffff330000-    6fffff45a000       Deferred        advapi32
PE-Wine     6fffff470000-    6fffffa6b000       Deferred        kernelbase
PE-Wine     6fffffa80000-    6fffffc36000       Dwarf-4-5       kernel32
PE-Wine     6fffffc50000-    6ffffffea000       Dwarf-4-5       ntdll
ELF         7fc4efad0000-    7fc4efafb000       Deferred        libnss_myhostname.so.2
ELF         7fc4efafb000-    7fc4efb28000       Deferred        libnss_resolve.so.2
ELF         7fc4efb28000-    7fc4efb4d000       Deferred        libgcc_s.so.1
ELF         7fc4efb4d000-    7fc4efb59000       Deferred        libcap.so.2
ELF         7fc4efb59000-    7fc4efbb5000       Deferred        libnss_mymachines.so.2
ELF         7fc4efbb5000-    7fc4efc09000       Deferred        libgssapi_krb5.so.2
ELF         7fc4efc09000-    7fc4efc10000       Deferred        libkeyutils.so.1
ELF         7fc4efc10000-    7fc4efc1e000       Deferred        libkrb5support.so.0
ELF         7fc4efc1e000-    7fc4efc24000       Deferred        libcom_err.so.2
ELF         7fc4efc24000-    7fc4efc52000       Deferred        libk5crypto.so.3
ELF         7fc4efc52000-    7fc4efd2a000       Deferred        libkrb5.so.3
ELF         7fc4efd37000-    7fc4efd40000       Deferred        kerberos.so
ELF         7fc4efd40000-    7fc4efd4b000       Deferred        libffi.so.8
ELF         7fc4efd4b000-    7fc4efdf1000       Deferred        libgmp.so.10
ELF         7fc4efdf1000-    7fc4efe3a000       Deferred        libhogweed.so.6
ELF         7fc4efe3a000-    7fc4efe92000       Deferred        libnettle.so.8
ELF         7fc4efe92000-    7fc4efea9000       Deferred        libtasn1.so.6
ELF         7fc4efea9000-    7fc4f0063000       Deferred        libunistring.so.5
ELF         7fc4f0063000-    7fc4f0085000       Deferred        libidn2.so.0
ELF         7fc4f0085000-    7fc4f0158000       Deferred        libzstd.so.1
ELF         7fc4f0158000-    7fc4f020a000       Deferred        libbrotlienc.so.1
ELF         7fc4f020a000-    7fc4f03a0000       Deferred        libp11-kit.so.0
ELF         7fc4f03a0000-    7fc4f05a4000       Deferred        libgnutls.so.30
ELF         7fc4f05a6000-    7fc4f05b1000       Deferred        secur32.so
ELF         7fc4f05b1000-    7fc4f05bd000       Deferred        bcrypt.so
ELF         7fc4f05cb000-    7fc4f05f6000       Deferred        libexpat.so.1
ELF         7fc4f05f6000-    7fc4f0646000       Deferred        libfontconfig.so.1
ELF         7fc4f0646000-    7fc4f06e1000       Deferred        libpcre2-8.so.0
ELF         7fc4f06e1000-    7fc4f0704000       Deferred        libbrotlicommon.so.1
ELF         7fc4f0704000-    7fc4f0727000       Deferred        libgraphite2.so.3
ELF         7fc4f0727000-    7fc4f0873000       Deferred        libglib-2.0.so.0
ELF         7fc4f0873000-    7fc4f0882000       Deferred        libbrotlidec.so.1
ELF         7fc4f0882000-    7fc4f0990000       Deferred        libharfbuzz.so.0
ELF         7fc4f0990000-    7fc4f09ca000       Deferred        libpng16.so.16
ELF         7fc4f09ca000-    7fc4f09dd000       Deferred        libbz2.so.1.0
ELF         7fc4f09dd000-    7fc4f09f7000       Deferred        libz.so.1
ELF         7fc4f09f7000-    7fc4f0ac5000       Deferred        libfreetype.so.6
ELF         7fc4f0ac5000-    7fc4f0bb2000       Deferred        libm.so.6
ELF         7fc4f0bb2000-    7fc4f0d54000       Deferred        win32u.so
ELF         7fc4f0d54000-    7fc4f0d65000       Deferred        libresolv.so.2
ELF         7fc4f0d69000-    7fc4f0d6f000       Deferred        crypt32.so
ELF         7fc4f145c000-    7fc4f148f000       Deferred        liblzma.so.5
ELF         7fc4f148f000-    7fc4f14a9000       Deferred        libunwind.so.8
ELF         7fc4f14a9000-    7fc4f1563000       Export          ntdll.so
ELF         7fc4f1566000-    7fc4f1748000       Deferred        libc.so.6
ELF         7fc4f174c000-    7fc4f1751000       Deferred        dnsapi.so
ELF         7fc4f1751000-    7fc4f1757000       Deferred        ws2_32.so
ELF         7fc4f1757000-    7fc4f178c000       Deferred        ld-linux-x86-64.so.2
ELF         7fc4f178c000-    7fc4f1791000       Deferred        <wine-loader>
Threads:
process  tid      prio    name (all IDs are in hex)
00000038 services.exe
	0000003c    0     
	00000040    0     wine_rpcrt4_server
	0000004c    0     wine_rpcrt4_io
	00000070    0     wine_rpcrt4_io
	00000090    0     wine_rpcrt4_io
	000000a4    0     wine_rpcrt4_io
	000000bc    0     wine_rpcrt4_io
	000000d0    0     
	00000100    0     wine_rpcrt4_io
00000044 winedevice.exe
	00000048    0     
	00000054    0     
	00000058    0     wine_sechost_service
	0000005c    0     
	00000060    0     
	000000c8    0     
	000000cc    0     
00000068 winedevice.exe
	0000006c    0     
	00000074    0     
	00000078    0     wine_sechost_service
	0000007c    0     
	00000080    0     
	00000088    0     
	0000009c    0     
	000000a0    0     
00000094 plugplay.exe
	00000098    0     
	000000a8    0     
	000000ac    0     wine_sechost_service
	000000b0    0     wine_rpcrt4_server
000000b4 svchost.exe
	000000b8    0     
	000000c0    0     
	000000c4    0     wine_sechost_service
000000f8 rpcss.exe
	000000fc    0     
	00000108    0     
	0000010c    0     wine_sechost_service
	00000110    0     wine_rpcrt4_server
	00000114    0     wine_rpcrt4_server
	0000021c    0     wine_rpcrt4_io
000001f4 start.exe
	000001f8    0     
000001fc (D) C:\Program Files (x86)\Farming Simulator 2022\dedicatedServer.exe
	00000200    0     
	00000220    0     
	00000224    0     
	0000022c    0     
	00000230    0     
	00000234    0     
	00000248    0 <== 
	00000270    0     
00000204 conhost.exe
	00000208    0     
0000020c explorer.exe
	00000210    0     
	00000214    0     
	00000218    0     wine_rpcrt4_server
0000024c FarmingSimulator2022Game.exe
	00000250    0     
	00000254    0     
	00000260    0     
	00000264    0     
	00000268    0     
	0000026c    0     
System information:
    Wine build: wine-9.0
    Platform: x86_64 (guest: i386)
    Version: Windows 10
    Host system: Linux
    Host version: 5.15.0-97-generic

**Comment by Toetje585** [comment]
Where there any mods installed?

Please share a bit more information on what kind of system this is running on.
