### ISSUE TITLE
Only able to connect to server via LAN network

### ISSUE THREAD

**Issue by georgefeakes** [wine-gameservers/arch-wine-fs22#12]
I've forwarded the server port 10823 for both UDP and TCP on my router but no luck allowing friends to join the server. On LAN the server works and can be connected to.

Also noticed that the docker-compose and docker run setups are slightly different. Is there a reason that port 9000 is used in the docker run version? Is this a mistake?

Any ideas about how to get my server public facing? I'm hosting on unRAID system via docker.

**Comment by Toetje585** [comment]
@georgefeakes Thanks for reaching out, I don't think this is a container/docker issue but something related to you port forwarding rules or someting between it. Port 9000 was an old port I just removed it thanks for pointing it out.

I supose you have more port forward rules due running unraid?

**Comment by georgefeakes** [comment]
I have a feeling this is something to do with the network setup of the container running on unraid. Will have to do some investigating. Just wanted to make sure that the port 9000 definitely wasn't used for anything and I hadn't missed this in my port forwarding rules.

**Comment by Toetje585** [comment]
@georgefeakes 

I suppose this can only happen if you define custom networks. Perhaps unraid ships with iptables?

**Comment by bugs181** [comment]
> I've forwarded the server port 10823 for both UDP and TCP on my router but no luck allowing friends to join the server. On LAN the server works and can be connected to.
> 
> Also noticed that the docker-compose and docker run setups are slightly different. Is there a reason that port 9000 is used in the docker run version? Is this a mistake?
> 
> Any ideas about how to get my server public facing? I'm hosting on unRAID system via docker.

Off topic, but how did you connect the FS22 client to the LAN IP? I'm looking into running my own dedicated server but for LAN purposes ONLY. I'm currently running tons of services on a CGNAT using tunneling and VPNs, etc - but seeing no way to do this with FS22.
