### ISSUE TITLE
What would need to be changed to support Steam version?

### ISSUE THREAD

**Issue by gentleadam** [wine-gameservers/arch-wine-fs22#15]
I'm new here, and new to hosting a server. Just doing some research. I have the Steam version of the game and could purchase another through another Steam account as it's the cheapest place to buy it.

What would need to change to make this image support Steam version?

**Comment by Toetje585** [comment]
Hallo,

Steam version cannot be used because steam itself is a dependency which you can not run in a docker environment.
Unless Giants ever release a steamcmd (real server).
