### ISSUE TITLE
Unraid support?

### ISSUE THREAD

**Issue by oliver989** [wine-gameservers/arch-wine-fs22#2]
Hi,

Thanks for putting this together.
Would it be possible to get this working in Unraid? Or maybe even added to the Unraid Apps section?
I am already running a couple of dedicated servers, but i do not know how to add a custom docker to Unraid.

**Comment by Toetje585** [comment]
https://github.com/wine-gameservers/docker-templates

:)

**Comment by oliver989** [comment]
Awesome, thank you!
