### ISSUE TITLE
Issue (I Think) With Latest Version

### ISSUE THREAD

**Issue by deggle** [wine-gameservers/arch-wine-fs22#3]
Hi, thanks for making this!

I've managed to get things going, and FS22 has installed. The script then proceeds to do the install of the Premium expansion, but I get an error saying it needs version 1.13 or greater. I get the same error if I manually try to run the DLC exe. I just downloaded the latest files which are 1.13.1 so this could be a GIANTS issue with their version checking...

Any ideas?

**Comment by deggle** [comment]
![image](https://github.com/wine-gameservers/arch-wine-fs22/assets/6651579/11042eb7-0af9-42c3-a430-3e1cab7531c2)

**Comment by deggle** [comment]
Also getting a "502 Bad Gateway" on the web admin port (correctly mapped etc) even when the server isn't running.
Don't think this is going to work for me - bit of a shame.
I'll leave this up in case someone does get chance to look at it, and in any event thanks for your work - it clearly has worked for some people!

**Comment by Toetje585** [comment]
Hello, Try again with the latest docker image :)

**Comment by deggle** [comment]
Thanks, that sorted it for me
Any way to specify the web GUI port? If I expose a different port in docker, it does a redirect to :8080 which I'm using for another service. I managed to get around this by giving the container it's own external network IP on the LAN, but it's a bit hacky. Appreciate this port number and redirect may be built into the software so may not be changeable.
Many thanks!

**Comment by Toetje585** [comment]
@deggle I wil try to add this option soon... I also use this port for something else.
