### ISSUE TITLE
Since updating the docker image to support the changes made for the AGI pack, I can no longer access the Web UI

### ISSUE THREAD

**Issue by georgefeakes** [wine-gameservers/arch-wine-fs22#6]
Since updating yesterday I am no longer able to view the admin Web UI to start and stop the server. According to the terminal window the server has started with no problems.

![image](https://github.com/wine-gameservers/arch-wine-fs22/assets/34819831/5db67471-fd35-4b83-8bb8-271532832190)

All the ports are the same and there has been no network changes. Any ideas?

**Comment by DJWoodZ** [comment]
It looks like nginx is not installed/running. You can confirm this by running this command on the host (you may need to use `sudo` with docker depending on your host config):

```sh
docker logs arch-wine-fs22 | grep nginx
```

As a temporary fix, you could try running this command on the host:

```sh
docker exec -it arch-wine-fs22 /bin/sh
```

And then this command in the container:

```sh
pacman -S nginx-mainline --noconfirm
```

**Comment by georgefeakes** [comment]
The first command stated that nginx was in a fatal state. I carried on with the next commands and then restarted the docker container. I can now access the admin Web UI again! Thanks for that - fingers crossed this isn't a recurring issue 🤞

**Comment by Toetje585** [comment]
Hello, thanks for the report i'm forcing the rebuild of the base and fs22 image as we speak. I'm not sure if it will fix it but I suspect as pacman -S nginx-mainline --noconfirm solved the issue for you something on archlinux side was borked yesterday.

**Comment by Toetje585** [comment]
Please confirm latest update has fixed the issue!

**Comment by georgefeakes** [comment]
When running the setup script I get a lot of errors now and it no longer automatically closes. Could this be related?

![image](https://github.com/wine-gameservers/arch-wine-fs22/assets/34819831/c08b1b44-77c8-4dc8-a772-95fd7cf75b36)

When I manually close the setup script and start the server script I am able to access the Web UI like normal.

**Comment by Toetje585** [comment]
@georgefeakes Those are not errors but wine debugging messages. I should disable them by default :)

**Comment by Toetje585** [comment]
This was a nginx bug, solved with the latest image.
